FROM rasa/rasa:3.1.0

WORKDIR /app

USER root

COPY actions/requirements-actions.txt ./
RUN pip install -r requirements-actions.txt

COPY ./actions /app/actions

RUN chmod +x /app/actions/rasa.sh

COPY ./.env /app/.env
COPY ./google_service_account_credentials.json /app/google_service_account_credentials.json

ENTRYPOINT []
CMD /app/actions/rasa.sh
