FROM rasa/rasa:3.1.0

USER root

WORKDIR /app

COPY . .

RUN pip install -r requirements.txt
RUN rasa train

ENTRYPOINT ["rasa"]
CMD ["run", "--model", "/app/models", "--enable-api", "--cors", "\"*\""]
