version: "3.1"
nlu:
- intent: nlu_fallback
  examples: |
    - ما مجموع 2+2؟
    - حكيم كم 2+2؟
    - كم عمرك؟
- intent: dont_know
  examples: |
    - لست ادري
    - لا اعلم
    - كيف اعلم
    - ما بدري
    - لا اعلم ولله
    - لست اعرف
    - لا ادري
    - لست اعلم
    - ما بعرف
    - لا اعرف
    - كيف اعرف
    - كيف ادري
    - ما بعرف ولله
- intent: greet
  examples: |
    - يا هلا
    - تحياتي
    - اهلا
    - مرحباا!
    - بدي مساعدة
    - ممكن خدمة
    - يا مراحب
    - مرحبا
    - هلا
    - يا اهلا و سهلا
    - مساء النور
    - اهلا بك
    - حياك الله
    - اهلا حكيم
    - صباح النور
    - تحية
    - السلام عليكم ورحمة الله وبركاته
    - السلام عليكم
    - مين معي
- intent: restart
  examples: |
    - ابتداء مرة اخرى
    - المحاولة من جديد
    - تجديد المحاولة
    - العودة
    - هناك خطأ هل من الممكن ان تعيد
    - من البداية
    - العودة للبداية
    - قم بالاعادة
    - الرجوع
    - اعادة المحاولة
    - اعادة
    - اعادة المحادثه
    - اعادة البدء
    - هل من الممكن ان تعيد
    - يجب ان نقوم بالاعادة
    - اعد البدء
    - اريد معاودة المحادثه
    - معاودة التشخيص
    - هل استطيع المعاوده؟
- intent: goodbye
  examples: |
    - خلص تمام
    - الى اللقاء
    - اشكرك كثيرا لقد ساعدتني
    - الوداع
    - تشرفت
    - مشكور
    - سعدت بلقائك
    - شكرا على المساعدة
    - سلام
    - يكثر من خيرك
    - نجميل. شكرا
    - مع السلامة
    - تمام. شكرا!
    - اشكرك
    - رائع. حسنا, مع القاء
    - سلامات
    - شكرا
    - تحية الوداع
    - شكرا ووداعا
    - شكرا جزيلا
    - يعطيك العافية
- intent: sex_report
  examples: |
    - أنا [شب]{"entity": "sex", "value": "male"}
    - [والدي]{"entity": "sex", "value": "male"}
    - [خالتي]{"entity": "sex", "value": "female"}
    - [خالي]{"entity": "sex", "value": "male"}
    - [زوجتي]{"entity": "sex", "value": "female"}
    - انا [بنت]{"entity": "sex", "value": "female"}
    - [طفلتي]{"entity": "sex", "value": "female"}
    - [مرتي]{"entity": "sex", "value": "female"}
    - جنسي [ذكر]{"entity": "sex", "value": "male"}
    - انا [بنوتة]{"entity": "sex", "value": "female"}
    - [انثى]{"entity": "sex", "value": "female"}
    - [طفلي]{"entity": "sex", "value": "male"}
    - [ولدي]{"entity": "sex", "value": "male"}
    - انا [فتى]{"entity": "sex", "value": "male"}
    - [ابي]{"entity": "sex", "value": "male"}
    - انا [ختيار]{"entity": "sex", "value": "male"}
    - [بنتي]{"entity": "sex", "value": "female"}
    - [زوجي]{"entity": "sex", "value": "male"}
    - انا [زلمة]{"entity": "sex", "value": "male"}
    - [عمي]{"entity": "sex", "value": "male"}
    - انا [ذكر]{"entity": "sex", "value": "male"}
    - انا [ولد]{"entity": "sex", "value": "male"}
    - انا [صبيه]{"entity": "sex", "value": "female"}
    - انا [عجوز]{"entity": "sex", "value": "male"}
    - جنسي هو [انثى]{"entity": "sex", "value": "female"}
    - [ابنتي]{"entity": "sex", "value": "female"}
    - انا [فتاة]{"entity": "sex", "value": "female"}
    - [بابا]{"entity": "sex", "value": "male"}
    - [عمتي]{"entity": "sex", "value": "female"}
    - [امي]{"entity": "sex", "value": "female"}
    - انا [فتاه]{"entity": "sex", "value": "female"}
    - انا [انثى]{"entity": "sex", "value": "female"}
    - [والدتي]{"entity": "sex", "value": "female"}
    - انا [امراة]{"entity": "sex", "value": "female"}
    - انا [رجل]{"entity": "sex", "value": "male"}
- intent: deny
  examples: |
    - اتوقع انك على خطأ
    - ما بتفق
    - ما تقوله ليس صحيح
    - لأ مش صح
    - لا اعتقد
    - ما بعتقد
    - خطا
    - خطئ
    - هذا ليس بصحيح
    - ما بتفق معك
    - انت محطئ
    - اعارض
    - نتعارض
    - ليس بصحيح
    - ليس صحيح
    - انت لست على صواب
    - ما تقوله مستحيل
    - هذا خاطئ بالتاكيد
    - ليس صحيح ما تقوله
    - خطأ
    - لا, غير صحيح
    - لسنا على اتفاق
    - غير صحيح
    - له غلط
    - غير ممكن
    - هذا مش صح
    - هيك مش صح
    - هذا خاطئ
    - ما تقوله خاطئ
    - مستحيل ما تقوله
    - ما تكتبه خاطئ
    - لا اظن
    - انت على خطأ
    - انا لا اوافق
    - انا اعارض
    - انت تقول خطأ
    - ما بظن
    - ليس واضح
    - مش صح يلي بتحكيه
    - غلط
    - مستحيل
    - لا اتفق
- intent: age_report
  examples: |
    - [ذكر]{"entity": "sex", "value": "male"}, عمري [30](age) سنه
    - عمري [30](age) عاما
    - [13](age) سنه
    - أبلغ من العمر [61](age) عام
    - عمرها [65](age) سنه
    - عمري [22](age) سنة
    - عمري [23](age) سنة
    - عمرها [31](age) عام
    - عمري [12](age) سنة
    - عمري [10](age) عام
    - عمري [42](age) سنة
    - عمري [50](age) عاما
    - [ذكر]{"entity": "sex", "value": "male"} وعمري [22](age) سنه
    - عمري [91](age) سنة
    - عمري [43](age) عام
    - عمرها [77](age) عام
    - عمري [18](age) سنة
    - عمري [88](age) سنة
    - أبلغ من العمر [80](age) سنة
    - عمري [19](age) سنة
    - تبلغ من العمر [48](age) سنه
    - عمري يساوي [63](age) سنة
    - عمري [11](age) عام
    - عمري [51](age) سنة
    - عمري [14](age) عام
    - عمري [66](age) سنة
    - عمري [21](age) عاما
    - عمري يقدر ب [31](age) سنه
    - عمري يساوي [12](age) عاما
    - عمري [22](age) عام
    - عمري هو [16](age) عاما
    - ابلغ من العمر [24](age) عام
    - عمري [19](age) عام
    - عمري [78](age) سنة
    - تبلغ من العمر [17](age) عام
    - عمري [51](age) عام
    - عمرها [88](age) عام
    - عمري يقدر [84](age) عاما
    - عمري [15](age) عام
    - انا [65](age) عام
    - عمره [95](age) سنة
    - عمري هو [99](age) سنه
    - عمرها هي [99](age) سنه
    - عمري [44](age) سنة
    - عمري [15](age) سنة
    - أبلغ من العمر [19](age) سنة
    - تبلغ من العمر [3](age) سنة
    - ابلغ من العمر [30](age) عام
    - عمري [11](age) سنة
    - عمري هو [18](age) سنة
    - العمر [30](age) سنه
    - عمري [14](age) سنة
    - ابلغ من العمر [18](age) سنة
    - أبلغ من العمر [67](age) عام
    - عمرها هي [91](age) سنه
    - عمري [18](age) عام
    - انا [41](age) سنة
    - عمري [21](age) سنة
- intent: affirm
  examples: |
    - صحيح
    - ما تقوله اكيد
    - اتفق على ما تقول
    - متقبل ما تقول
    - رايك سديد
    - توقعك صحيح
    - صح ما قلت
    - بالتاكيد
    - هذا حقيقي
    - ما تقوله هو الصواب
    - اه
    - ظنك في مكانه
    - نحن على اتفاق
    - متقبل
    - اقبل
    - انت على صواب
    - انا اعتقد انك صحيح
    - انا اعتقد ان ما تقوله صحيح
    - اتفق
    - على كامل التأكيد
    - اؤكد على ذلك
    - صح
    - وافقت
    - ما تقوله يميل للصحة
    - سديد
    - قبول
    - واضح
    - اصبت
    - اتفق على هذا
    - اظن
    - منطق
    - متاكد من ذلك
    - قبلت
    - انت على حق
    - اعتقد انك على حق
    - مع تشديد
    - هذا واضح
    - اتوقع
    - انت صحيح
    - ما تقوله حقيقي
    - التنبؤ في مكانه
    - تنبؤك صحيح
    - صواب
    - اؤكد على صحة الامر
    - ما تقوله حقيقة
    - انت على منطق
    - هذا اكيد
    - جوابك منطقي
    - نحن على وفاق
    - ما تقوله قريب من المنطق
    - انت صائب
    - اتنبأ بالصحة
    - مضبوط
    - متأكد
    - ما تقوله سديد
    - انا على قبول
    - اقبل ما تقوله
    - اعتقد
    - انا اتوقع انه صحيح
    - نعم
    - حقيقي
    - ما تقوله صحيح
    - اعتقد ذلك
    - هذه حقيقة
    - مؤكد
    - نعم, صحيح
    - صائب
- intent: observations_report
  examples: |
    - هناك الكثير من الاعراض التي اعاني منها فقدان الشهيه حرقه والام في المعده والام في المفاصل فقدان الوزن دوخه ونسيان وارهاق بدني...
    - [والدتي]{"entity": "sex", "value": "female"} تعاني من الم في المرارة كيفية علاج
    - اعاني من تجشؤات واصوات مسموعة في البطن و الم في الجانب الايمن من البطن
    - اعانى دائما من الم المعده من زمن بعيد ويكون الالم مصاحب التقئ غالبا والاسهال او الامساك ولكننى اعانى من الامساك طوال الوقت
    - بطني بوجعني
    - انا بعاني من انه عيوني بصيرو يدمعو بطريقة مزعجة خاصة بفصل الصيف و لما اتعرض لنسيم هواء
    - مرحبا دكتور انا يعاني من تشوش في الرؤيه وعدم التركيز احيانا مالسبب هل ضعف بالبصر؟
    - كنت اعاني من صعوبة الهضم
    - اشعر بوجود تعب في المعده وعند ما يحدث لي زكام تاتي لي الغصه واشعر بالقئ
    - عيوني تدمع طوال الوقت
    - ضيق في مخرج المعدة
    - انا اعاني من ترهل الجفون العلوية
    - انا اعاني من حكه وتورم واحمرار في العين اليسرى واحياناً في اليمنى ، وتصاحبها احتقان في الانف وحكه في الاذن. للعلم اني عندي حساسيه في القصبات الهوائيه مزمنه؟
    - اشعر بالم بالعين عند نظر شخص لي من قريب واواجه بعض مثل هذا الالم في القراءة من الكتب ما المسبب؟
    - اعاني من الم في العصب الموجود مابين العين والحاجب ارجو وصف الحالة والعلاج
    - أنا توجعني معدتي
    - ما زال لدي الم شديد في المعده
    - حراره عاليه في البطن والاكتاف مع الم اسفل البطن من الجهه اليسرى
    - عمري [42](age) عندي حساسية في العينين ولا احس بها الا في ايام الحيض وهي تسبب لي ضعف في النظر
    - مرحبا [ابني]{"entity": "sex", "value": "male"} عنده فوق العين مثل حبة حمراء كبيرة كيف أتخلص منها؟
    - عندي تورم باللسان من الامام والجوانب وتشق من الاعلي ويكون ساعات مؤلم
    - الألم من رأس المعده
    - اعاني من تعتم يسبب عدم وضوح الرؤية بشكل جيد
    - إجابتي من اهل الاختصاص أعاني من ظبابية في الرؤية في العين اليمنى وزرت الطبيب وفحصني وقام بتصوير عيني و أخبرني انه لدي انتفاخ في شبكية العين.
    - السلام عليكم اعاني من داء الشقيقة عندما تأتي النوبه تبدأ عيناي تدمع ماهو سبب
    - اعاني من الم شديد في فم المعده اعلي البطن
    - مرحباً في بعيني قريب المدمع دائرة كيس دهني لو هي كيس دهني شو يكون علاجها؟
    - عندي جفاف بالعين مستمرمن ودائما استخدم قطرات مرطب من دون فائدة
    - ظهرت في ساقي خطين بيضاء اللون تقريبا 10 سم طول كل خط ما هو سببها؟
    - اشعر ب طقطقة و صوت بالعيون عند فتحها و اغلاقها ولكن ليس بشكل دائما ما السبب و ما الحل ؟
    - عندي مشكله في الهضم
    - اعاني من قولون هضمي واسهال وخروج الدم مع البراز
    - عيني بتفرز كتير من الدموع شو الحل؟؟!
    - السلام عليكم اعاني من التجاعيد اسفل واعلى العيون ما الحلول لذهابها؟
    - اعاني من تشنجات في القولون العصبي
    - اعاني من بعض السمنة أشعر ببعض الاوجاع الخفيفة على مستوى البطن من الجهة اليسرى تحت القفص الصدري...
    - اعاني من شعور بالغثيان
    - بعاني دايما من وجع ف المفاصل وكسل طول اليوم وارهاق شديد
    - اشعر بوجود نقطة سوداء اثناء النظر تذهب في كل الاتجاهات ما السبب وهل هو مرض ام ماذا
    - اعاني من وجود نقاط سوداء على بياض عيني فهل لها تأثير على العين مستقبلا علما انني اعاني من قصر النظر ايضا
    - حلقي يئلمني جدا
    - دكتور انا راسي يؤلمني كثيرا. [ذكر]{"entity": "sex", "value": "male"}
    - عمري [31](age) عاما, واعاني من وجع بطن شديد
    - وعندي الم فوق الصدر جهه اليسار
    - [أختي]{"entity": "sex", "value": "female"} عندما تأكل تحس حلقها يجف و لا تستطيع تبلع الطعام والشراب أو تتنفس
    - عندي الم اسفل الصدر يسار
    - لدي الم في عين عند روية شمس او الأنوار او روية شي في مكان عالي تنزل مني دموع كثيره والم في وسط العين
    - كنت بعاني من وجع شديد اعلي البطن وخنقه وعدم القدره علي التنفس
    - عندما اسعل او استلقي على جنبي او ظهري احس بالم في الامعاء
    - اعاني احيانا من الم في القولون
    - اعاني من الكيس الدهني في عيني اليمنى
    - اشكو من روية غبار عند النظر وخروج دمع كثير مع وجع
    - أعاني من مرض السكري وأصبحت أعاني من مشاكل في عيني بسبب ارتفاع مخزون السكر ماذا افعل؟
    - أشعر بالم أسفل الصدر في الجهة اليسرى منذ فترة من الاعراض التي تضهر جراء هذا الالم الشعور بالدوار الشعور بالاختناق تنمل الاطراف القلق الشديد التبول بكثرة تنمل الجهة اليسرى خاصة في الرقبة
    - كيف ممكن نتخلص من الحرقة بالعين و الاحمرار البسيط المصحوب معها
    - حكه في العيون ولون احمر ودموع بعد الحك ويش الدواء المناسب
    - لم أعد أستطيع قراءة الأشياء بها أو تمييز الوجوه فهل يجب علي زيارة الطبيب ليصف لي نظاراتنظارات
    - عندي اصفرا ر في العين شو الحل انا عمري [14](age) سنة
    - انا اعاني من الألم في الظهر وفي الاكتاف وبين الاكتاف وعندما ابتلع الطعام أشعر بالألم الظهر والاكتاف وحتى اضطرابات في الرؤيه
    - اعاني من تغير في فتحة العين اليمنى ولايوجد اي مشكلة بالنظر فقط فتحة العين اصبحت اصغر بقليل من اليسرى هل هناك علاج معين
    - عند اصابتي بالانلفونزة تحمر وتنتفخ العين اليسر هل هدا يعود لحساسية؟
    - دايما في اول فصل الشتا بعاني من جفاق ودموع متواصة من عيوني وحكة شو السبب
    - انا [ذكر]{"entity": "sex", "value": "male"} بعمر ال [15](age), واعاني من سعال وحمه شديدتان
    - طلعلي كرة عند مدمع العين شو ممكن تكون وكيف ممكن أتخلص منها
    - لي ألم فى معدتي غازات كثيره ومغير رائحه العرق
    - اعانى من صداع شبه دائم وضغطي منخفض وحاليا
    - دكتور انا [راسي](sex) يؤلمني كثيرا. [ذكر]{"entity": "sex", "value": "male"} بعمر ال [40](age)
    - انا اعانى من الم بالمعده منذ فترة ظهر الم المفاصل والقلق والتوتر
    - أشكو من حرقان في العين وإحمرار وإنفاخ فى الجفون مع تدميع مستمر منذ أكثر من أسبوع
    - طفي عمره [3](age) سنوات يعاني من الام بالمعده
    - عندي مشكلة في البطن غازات وانتفاخ والأم في البطن
    - الم البطن استبراد وما هوه العلاج
    - اشكو من آلام بالمعده اعلى المده
    - اعاني اصفرار العيون في المنطقة البيضاء
    - [زوجتي]{"entity": "sex", "value": "female"} تعاني منذ زمن بعيد من غثيان و تقيؤ وفقدان الشهية في بعض الاحيان بدون الشعور بالم في المعدة او اي جزء من الجهاز الهضمي
    - [أمي]{"entity": "sex", "value": "female"} تعاني من الم شديد في بطنها وفقدان الشهية واذا تناولت طعام او مشروب تشعر بأن بطنها تعتصرها وعدم القدرة على اخراج الغازات وانتفاخ في البطن
    - مرحبا. عمري [30](age) سنه. [ذكر]{"entity": "sex", "value": "male"}. اعاني من الام شديده جدا جدا بالمعده
    - اعاني من امراض كثيره
    - العين المخروطية وعلاجها هل هي خطير يمكن علاجها بشكل جيد
    - اصابني امبارحه سعال وقحه شديدان جدا
    - حلقي يؤلمني جدا
    - انا عندي اوجاع معدة مع اوجاع بطن وانا بتنفس بحس باوجاع
    - اعاني من الامساك الشديد
    - عمري [31](age) عاما ورأسي يؤلمني جدا
    - انا كتير بيحصلي صداع في دماغي واشعر بالدوخان في بعض الأحيان وخاصة اثناء المذاكرة لا اعلم لماذا ؟!اريد طبيب
    - [والدي]{"entity": "sex", "value": "male"} يبلغ من العمر [78](age) عاما يعاني من الإمساك الشديدالمزمن ، هو مريض سكري و بروسطاطا يعاني من الإجهاد دائما فهو اصبح غير قادر على التحرك بشكل جيد يعاني من انتفاخ شديد جدا و غير قادر للذهاب الى الطبيب...
    - مند اسبوع يعاني [ابني]{"entity": "sex", "value": "male"} من تجشئات برائحة الكبريت مع قيء متكرر
    - درجة حرارتي مرتفعه جدا. انا [ذكر]{"entity": "sex", "value": "male"}
    - أنا أعاني من الغازات و حرقة الأمعاء المستمرة في البداية كانت هذه الحالة تزعجني بسبب الإنتفاخ و الشعور بالإمتلاء في منطقة البطن بالإضافة إلى الآلام و المغص
    - [والدي]{"entity": "sex", "value": "male"} بعمر ال [140](age) ويشعر بحرقه شديده بمعدته
    - منذ أسابيع ظهرت لي حبة فوق عيني اليمنى ثم بعدها في أسفل عيني اليسرى ماذا أفعل لتزول هذه الحبوب
    - أشعر بألم في اعصاب يدي ورجلي وعندي إمساك
    - السلام عليكم اعاني من حرارة المعدة وحرقه في المري مع صعوبة في التنفس
    - اعاني من ضعف القراءة و صعوبة في النظر عن بعد, ما الحل؟
    - عيني اليسار تذهب وبها حول كما لم أعد أستطيع قراءةالأشياء بها أو تمييز الوجوه فهل يجب علي زيارة الطبيب ليصف لي نظارات
    - اعاني من حساسة و التهاب، دون فائدة بسبب التعب و الارهاق و قلة نوم
    - السلام عليكم منذ سنة تقريبا تغيرت رائحة العرق والنفس لدي الى رائحة قوية وكريهة تسبب العطس والرغبة في شرب الماء لدى من يشتمها ...
    - اشعر بحمه, عطش شديد, سعال, وحراره عاليه
    - عمري [40](age) سنه. [ذكر]{"entity": "sex", "value": "male"}. واعاني من سعال شديد جدا, ومشاكل بالرؤيه
    - مؤخرا بدأت أحس بأن عيني اليسرى تنكمش او ترف لا اراديا لا ادري ما السبب و هل هذا شيء خطير؟ ارجو المساعدة
    - أنا اوجعني معدتي
    - [طفله]{"entity": "sex", "value": "female"} عمرها [3](age) سنوات تعاني من السعال والحمى واصفرار العينين وتبكي
    - كيف أتخلص من اللون الأبيض المصفر في العيون وجعلها بيضاء نقيةعلما بان الاصفرار ليس نتيجة مرض
    - عندي احمرار شديد بالعين هل ليه حل ارجو الافاده
    - اشعر بالم في الاعين ولا استطيع فتحهما في بعض الحيان
    - [طفلي]{"entity": "sex", "value": "male"} له مغص شديد
    - عملت عمليه لعيني اليسرى عمليه زرع عدسه من جديديوجد الم شديد في العين استيقظ من النوم افتح عيني بصعوبه الرجاء المساعده
    - أشعر بألم في اعصاب يدي ورجلي بعد انتهائي من التغوط أعزكم الله حتى عندما احمل الهاتف او أشياء خفيفة فإني اشعر بهذا الألم وكأنه شئ ثقيل ثم يختفي الألم بعد ساعات او بعد يوم، فما سبب ذلك؟ علما ان عندي إمساك من فترة لفترة فاحيانا اجلس 3 ايام بدون عمل حما
    - اعاني من الامساك الشديد ارجو وصف اطعمه ومشروبات علي الاكثار منها واخري علي تجنبها
    - آلام المفاصل
    - [طفلي]{"entity": "sex", "value": "male"} عمره [3](age) سنوات ويعاني من الام بالمعده
    - دكتور اتمنى ان ترد على سؤالي هو سبب اصفرار بياض العين لان كلتا عيني فيهما اصفرار وهل يوجد علاج لذلك؟
    - بعاني من احمرار العين مع الحرقان ارجو الرد
    - برز لدى ابنتي الرضيعه انتفاخ في الجفن العلوي للعين اليمنى
    - تعرضت لحادث حيث حصل لي نزيف خارجي و نزيف داخلي برأسي نتيجة الإصابة بالرأس مما أدى إلى الدخول في غيبوبة و نتج عن ذلك فقدان البصر من أحد العينين (اليسرى) و بعد الفحوصات العديدة هل يوجد تشخيص؟
- synonym: male
  examples: |
    - ذكر
    - ولد
    - شب
    - حج
    - زلمة
    - رجل
    - فتى
    - ختيار
    - عجوز
    - زوجي
    - عمي
    - خالي
    - ولدي
    - ابني
    - طفلي
    - والدي
    - ابي
    - ابوي
    - بابا
- synonym: female
  examples: |
    - انثى
    - بنت
    - صبية
    - حجة
    - فتاة
    - فتاه
    - بنوتة
    - صبيه
    - امراة
    - مرأة
    - زوجتي
    - عمتي
    - خالتي
    - زوجة
    - مرتي
    - بنتي
    - طفلتي
    - ابنتي
    - والدتي
    - امي
    - ماما
    - أختي
    - أمي
    - طفله
