version: "3.1"
nlu:
- intent: dont_know
  examples: |
    - كيف ادري
    - لست ادري
    - كيف اعرف
    - ما بعلم
    - ما بدري
    - كيف اعلم
    - لست اعرف
    - لا اعرف
    - لا ادري
- intent: greet
  examples: |
    - اهلا بك
    - بدي مساعدة
    - اهلا
    - مساء الخير
    - حياك الله
    - صباح الخير
    - السلام عليكم
    - مين معي
    - يا اهلا و سهلا
    - السلام عليكم ورحمة الله وبركاته
    - تحية
    - صباح النور
    - مرحبا
    - هلا
    - ممكن خدمة
- intent: goodbye
  examples: |
    - اشكرك كثيرا لقد ساعدتني
    - شكرا جزيلا
    - الى اللقاء
    - شكرا ووداعا
    - خلص تمام
    - شكرا على المساعدة
    - سعدت بلقائك
    - يكثر من خيرك
    - سلام
    - وداعا
    - الوداع
    - اشكرك
    - مشكور
    - تشرفت
    - سلامات
    - شكرا
- intent: restart
  examples: |
    - اعادة المحاولة
    - اعادة
    - اعادة البدء
    - الرجوع
    - هل من الممكن ان تعيد
    - اعد البدء
    - العودة للبداية
    - ابتداء مرة اخرى
    - بدئ من جديد
    - هناك خطأ هل من الممكن ان تعيد
    - المحاولة مرة اخرى
    - يجب ان نقوم بالاعادة
    - تجديد المحاولة
    - معاودة
    - من البداية
    - العودة
- intent: sex_report
  examples: |
    - [ابي]{"entity": "sex", "value": "male"}
    - [زوجتي]{"entity": "sex", "value": "female"}
    - [عجوز]{"entity": "sex", "value": "male"}
    - أنا [صبية]{"entity": "sex", "value": "female"}
    - جنسي هو [انثى]{"entity": "sex", "value": "female"}
    - [عمتي]{"entity": "sex", "value": "female"}
    - [بنتي]{"entity": "sex", "value": "female"}
    - [زوجة]{"entity": "sex", "value": "female"}
    - [ماما]{"entity": "sex", "value": "female"}
    - انا [حج]{"entity": "sex", "value": "male"}
    - [طفلي]{"entity": "sex", "value": "male"}
    - [زوجي]{"entity": "sex", "value": "male"}
    - [ابنتي]{"entity": "sex", "value": "female"}
    - [ولدي]{"entity": "sex", "value": "male"}
    - أنا [شب]{"entity": "sex", "value": "male"}
    - [عمي]{"entity": "sex", "value": "male"}
    - انا [زلمة]{"entity": "sex", "value": "male"}
    - انا [امراة]{"entity": "sex", "value": "female"}
    - انا [ختيار]{"entity": "sex", "value": "male"}
    - [مرتي]{"entity": "sex", "value": "female"}
    - [والدي]{"entity": "sex", "value": "male"}
    - انا [فتاه]{"entity": "sex", "value": "female"}
    - انا [فتاة]{"entity": "sex", "value": "female"}
    - انا [رجل]{"entity": "sex", "value": "male"}
    - انا [انثى]{"entity": "sex", "value": "female"}
    - [امي]{"entity": "sex", "value": "female"}
    - [طفلتي]{"entity": "sex", "value": "female"}
    - انا [مرأة]{"entity": "sex", "value": "female"}
    - انا [حجة]{"entity": "sex", "value": "female"}
    - انا [بنت]{"entity": "sex", "value": "female"}
    - انا [فتى]{"entity": "sex", "value": "male"}
    - انا [ذكر]{"entity": "sex", "value": "male"}
    - انا [عجوز]{"entity": "sex", "value": "male"}
    - [خالتي]{"entity": "sex", "value": "female"}
- intent: deny
  examples: |
    - لا اتفق
    - يلي بتحكيه مش صح
    - ما تقوله مش صح
    - انا اعارض
    - مش صح يلي بتحكيه
    - خطئ
    - غير ممكن
    - انا لا اوافق
    - مستحيل ما تقوله
    - ما تكتبه خاطئ
    - لسنا على اتفاق
    - ليس بصحيح
    - نحن لسنا على وفاق
    - انت على خطأ
    - نتعارض
    - هذا ليس بصحيح
    - ليس صحيح ما تقوله
    - لا اعتقد
    - انت لست على صواب
    - ليس واضح
    - ما تقوله مستحيل
    - مش صح
    - هذا ليس صحيح
    - هذا مش صح
    - اتوقع لا
    - ما بعتقد
    - لا
    - هذا خاطئ بالتاكيد
    - هيك مش صح
    - خطا
    - غير صحيح
    - ما تقوله ليس صحيح
    - ما بظن
    - انت تقول خطأ
    - محطئ
    - انت محطئ
    - ليس صحيح
    - ما تقوله خاطئ
    - لا اظن
- intent: age_report
  examples: |
    - عمره [95](age) سنة
    - عمري [51](age) عام
    - عمرها [16](age) عام
    - عمري [18](age) سنة
    - أبلغ من العمر [67](age) عام
    - عمرها [31](age) عام
    - عمري يساوي [12](age) عاما
    - عمري هو [99](age) سنه
    - عمري [51](age) سنة
    - عمري [11](age) سنة
    - عمري يساوي [71](age) سنه
    - عمري [26](age) سنة
    - عمري [42](age) سنة
    - عمري [12](age) عام
    - عمري [14](age) سنة
    - انا [42](age) سنه
    - ابلغ من العمر [24](age) عام
    - ابلغ من العمر [30](age) عام
    - عمري [66](age) سنة
    - عمري [15](age) عام
    - عمري [81](age) سنة
    - عمري يقدر ب [36](age) سنة
    - عمري [14](age) عام
    - عمري يساوي [63](age) سنة
    - عمري [19](age) سنة
    - عمري [12](age) سنة
    - عمرها [77](age) عام
    - انا [65](age) عام
    - عمري [21](age) سنة
    - عمرها هي [91](age) سنه
    - عمرها [65](age) سنه
    - ابلغ من العمر [18](age) سنة
    - عمري [43](age) عام
    - عمري [91](age) سنة
    - أبلغ من العمر [19](age) سنة
    - عمري [11](age) عام
    - عمري [44](age) سنة
    - عمري [19](age) عام
    - عمره [68](age) سنه
    - تبلغ من العمر [17](age) عام
    - عمري [78](age) سنة
    - عمري [15](age) سنة
    - أبلغ من العمر [80](age) سنة
    - عمري [88](age) سنة
    - عمري هو [16](age) عاما
    - عمرها [41](age) سنة
    - تبلغ من العمر [48](age) سنه
    - عمري [18](age) عام
    - أبلغ من العمر [61](age) عام
    - عمرها هي [99](age) سنه
- intent: affirm
  examples: |
    - اعتقد انك على حق
    - اظن
    - اشدد
    - اتفق على هذا
    - انت على صواب
    - اتنبأ بالصحة
    - صواب
    - ما تقوله يميل للصحة
    - نعم
    - جوابك منطقي
    - ظنك في مكانه
    - اصبت
    - منطقي
    - هذا حقيقي
    - اقبل
    - قبول
    - متقبل
    - انت صائب
    - اؤكد على ذلك
    - بالضبط
    - ما تقوله انت صحيح
    - مع تشديد
    - صح
    - بالتاكيد
    - هذا واضح
    - متاكد من ذلك
    - هذه حقيقة
    - تنبؤك صحيح
    - انت صحيح
    - اؤكد على صحة الامر
    - انت على منطق
    - متأكد
    - انا اعتقد انك صحيح
    - انا اشدد
    - بالزبط
    - اعتقد
    - اقبل ما تقوله
    - مزبوط
    - حقيقي
    - ما تقوله قريب من المنطق
    - ما تقوله صحيح
    - اتنبأ بصحة الامر
    - سديد
    - التنبؤ في مكانه
    - متقبل ما تقول
    - صح ما قلت
    - ما تقوله قريب من الحقيقة
    - موافق
    - اتفق على ما تقول
    - ما تقوله حقيقي
    - صحيح
    - رايك سديد
    - مضبوط
    - على كامل التأكيد
    - هذا اكيد
    - ما تقوله هو الصواب
    - اكيد ما تقوله
    - انا على تقبل
    - قبلت
    - مؤكد
    - توقعك في مكانه
    - نحن على وفاق
    - واضح
    - انا على قبول
- intent: observations_report
  examples: |
    - [أختي]{"entity": "sex", "value": "female"} عمرها [51](age) سنة و بعض الأحيان عندما تأكل تحس حلقها يجف و لا تستطيع تبلع الطعام والشراب أو تتنفس
    - اعاني من تعتم يسبب عدم وضوح الرؤية بشكل جيد
    - وعندي الم فوق الصدر جهه اليسار
    - اعاني من شعور بالغثيان
    - مرحبا [ابني]{"entity": "sex", "value": "male"} عنده فوق العين مثل حبة حمراء كبيرة كيف أتخلص منها؟
    - عندي الم اسفل الصدر يسار
    - آلام المفاصل
    - اعانى من صداع شبه دائم وضغطي منخفض وحاليا
    - لدي الم في عين عند روية شمس او الأنوار او روية شي في مكان عالي تنزل مني دموع كثيره والم في وسط العين
    - أنا توجعني معدتي
    - اعاني من حساسة و التهاب، دون فائدة بسبب التعب و الارهاق و قلة نوم
    - أعاني من انتفاخ العين اليسرى و العصب الذي فوق الأذن اليسرى المتصل بالعين إلى رأسي من كذلك نصف رأسي يؤلمني كثيرا
    - ضيق في مخرج المعدة
    - اعاني من تشنجات في القولون العصبي
    - عندي مشكله في الهضم
    - اعانى من الكسل والخمول الدائم وقلة النشاط وانعدام الطاقة وسرعة ضربات القلب احيانا واشعر بالتعب الدائم طول الوقت رغم بذل اى مجهود رغبة ملحة بالنوم حتى بعد الاستيقاظ منه والشعور بأن الجسم لم يأخذ كفايته بالنوم رغم طول عدد ساعات النوم
    - أشعر بألم في اعصاب يدي ورجلي وعندي إمساك
    - اعاني من تغير في فتحة العين اليمنى ولايوجد اي مشكلة بالنظر فقط فتحة العين اصبحت اصغر بقليل من اليسرى هل هناك علاج معين
    - بعاني من احمرار العين مع الحرقان ارجو الرد
    - اعاني من اضراب القولون العصبي
    - لدي الم بطن
    - اعاني من بعض السمنة أشعر ببعض الاوجاع الخفيفة على مستوى البطن من الجهة اليسرى تحت القفص الصدري...
    - منذ فترة ٦ أشهر اعاني من وجع راس مزمن في داخل راسي أشعر بالوجع في دماغي مع وجع في الرقبة وثقل راسي على رقبتي لا استطيع تحمله، بالإضافة للغثيان طوال الوقت قبل او بعد الأكل،
    - عيني بتفرز كتير من الدموع شو الحل؟؟!
    - السلام عليكم اعاني من حرارة المعدة وحرقه في المري مع صعوبة في التنفس
    - عند اصابتي بالانلفونزة تحمر وتنتفخ العين اليسر هل هدا يعود لحساسية؟
    - [أختي]{"entity": "sex", "value": "female"} عندما تأكل تحس حلقها يجف و لا تستطيع تبلع الطعام والشراب أو تتنفس
    - اعاني من ضعف القراءة و صعوبة في النظر عن بعد, ما الحل؟
    - اعاني من التهاب مزمن بالمعدة وتغيرات تفاعليه في البنكرياس  .
    - [امي]{"entity": "sex", "value": "female"} صار عدهة نزيف من الشرج قوي مع الخروج والم اسفل البطن
    - انا عمري [45](age) سنة معاناتي من ثلاث سنوات وانا شتكي من الباطنيه بسبب الم وانتفاخات ورتجاع المري...
    - اشكو من آلام بالمعده اعلى المده
    - في كتير مرات بصير احس غباش بعيني بعدش قادرة اعمل اشي شو ممكن يكون السبب؟
    - أنا أعاني من الغازات و حرقة الأمعاء المستمرة في البداية كانت هذه الحالة تزعجني بسبب الإنتفاخ و الشعور بالإمتلاء في منطقة البطن بالإضافة إلى الآلام و المغص
    - كيف أتخلص من اللون الأبيض المصفر في العيون وجعلها بيضاء نقيةعلما بان الاصفرار ليس نتيجة مرض
    - انا اعاني من ترهل الجفون العلوية
    - ظهرت في ساقي خطين بيضاء اللون تقريبا 10 سم طول كل خط ما هو سببها؟
    - انا عندي اوجاع معدة مع اوجاع بطن وانا بتنفس بحس باوجاع
    - اعانى كثيرا من الكيس الدهني فى العين
    - اشعر بالم بالعين عند نظر شخص لي من قريب واواجه بعض مثل هذا الالم في القراءة من الكتب ما المسبب؟
    - كنت اعاني من صعوبة الهضم
    - اشعر بوجود تعب في المعده وعند ما يحدث لي زكام تاتي لي الغصه واشعر بالقئ
    - اشعر بي قيء بعد لاكل مباشر و احيان بحس بي الام شديده في الجزء العلوي من المعده وإرهاق شديد
    - عندي جفاف بالعين مستمرمن ودائما استخدم قطرات مرطب من دون فائدة
    - لي ألم فى معدتي غازات كثيره ومغير رائحه العرق
    - مرحبا دكتور انا يعاني من تشوش في الرؤيه وعدم التركيز احيانا مالسبب هل ضعف بالبصر؟
    - [طفلي]{"entity": "sex", "value": "male"} له مغص شديد
    - اعاني اصفرار العيون في المنطقة البيضاء
    - بعاني دايما من وجع ف المفاصل وكسل طول اليوم وارهاق شديد
    - اعاني منذ زمن من مشاكل في البطن
    - اعاني من الم شديد في فم المعده اعلي البطن
    - السلام عليكم اعاني من ألم بالعينين بالصباح ويزيد معا النظر الشمس
    - اعاني من الكيس الدهني في عيني اليمنى
    - اعاني من الم في العصب الموجود مابين العين والحاجب ارجو وصف الحالة والعلاج
    - أشعر بألم في اعصاب يدي ورجلي بعد انتهائي من التغوط أعزكم الله حتى عندما احمل الهاتف او أشياء خفيفة فإني اشعر بهذا الألم وكأنه شئ ثقيل ثم يختفي الألم بعد ساعات او بعد يوم، فما سبب ذلك؟ علما ان عندي إمساك من فترة لفترة فاحيانا اجلس 3 ايام بدون عمل حما
    - اشعر بوجود نقطة سوداء اثناء النظر تذهب في كل الاتجاهات ما السبب وهل هو مرض ام ماذا
    - انا اعاني من حكه وتورم واحمرار في العين اليسرى واحياناً في اليمنى ، وتصاحبها احتقان في الانف وحكه في الاذن. للعلم اني عندي حساسيه في القصبات الهوائيه مزمنه؟
    - عندي تورم باللسان من الامام والجوانب وتشق من الاعلي ويكون ساعات مؤلم
    - اعاني من الامساك الشديد
    - اعاني من الامساك الشديد ارجو وصف اطعمه ومشروبات علي الاكثار منها واخري علي تجنبها
    - اشعر بالم في الاعين ولا استطيع فتحهما في بعض الحيان
    - اعاني من انتفاخ في البطن وغازات وامساك وتجشوء.
    - مؤخرا بدأت أحس بأن عيني اليسرى تنكمش او ترف لا اراديا لا ادري ما السبب و هل هذا شيء خطير؟ ارجو المساعدة
    - انا اعانى من الم بالمعده منذ فترة ظهر الم المفاصل والقلق والتوتر
    - الأعراض اصفرار الجسم والعينين بشكل بسيط لون البول متغير مع حرقة في المثانة وآلام في المعدة
    - عندى مشكلة في عينى دايما اول ما تتعرض للهواأو الشمس بتدمع
    - اشكو من روية غبار عند النظر وخروج دمع كثير مع وجع
    - عندما اسعل او استلقي على جنبي او ظهري احس بالم في الامعاء
    - حراره في عيني فجائيه مع الم وتدمع واحيانااشعر بثقل في جفوني ولكن نظري سليم فما السبب
    - السلام عليكم منذ سنة تقريبا تغيرت رائحة العرق والنفس لدي الى رائحة قوية وكريهة تسبب العطس والرغبة في شرب الماء لدى من يشتمها ...
    - عمري [42](age) عندي حساسية في العينين ولا احس بها الا في ايام الحيض وهي تسبب لي ضعف في النظر
    - اعاني من وجود نقاط سوداء على بياض عيني فهل لها تأثير على العين مستقبلا علما انني اعاني من قصر النظر ايضا
    - أعاني من مرض السكري وأصبحت أعاني من مشاكل في عيني بسبب ارتفاع مخزون السكر ماذا افعل؟
    - انا صار لي سنه عندي الام في المعده والام في منتصف والام فم المعده وامساك واشعر عند الجوع الشديد بتقلصات بالمعده والقولون
    - أشكو من حرقان في العين وإحمرار وإنفاخ فى الجفون مع تدميع مستمر منذ أكثر من أسبوع
    - دكتور اتمنى ان ترد على سؤالي هو سبب اصفرار بياض العين لان كلتا عيني فيهما اصفرار وهل يوجد علاج لذلك؟
    - اعاني من قولون هضمي واسهال وخروج الدم مع البراز
    - عيني اليسار تذهب وبها حول كما لم أعد أستطيع قراءةالأشياء بها أو تمييز الوجوه فهل يجب علي زيارة الطبيب ليصف لي نظارات
    - انا كتير بيحصلي صداع في دماغي واشعر بالدوخان في بعض الأحيان وخاصة اثناء المذاكرة لا اعلم لماذا ؟!اريد طبيب
    - برز لدى ابنتي الرضيعه انتفاخ في الجفن العلوي للعين اليمنى
    - كنت بعاني من وجع شديد اعلي البطن وخنقه وعدم القدره علي التنفس
    - [أمي]{"entity": "sex", "value": "female"} تعاني من الم شديد في بطنها وفقدان الشهية واذا تناولت طعام او مشروب تشعر بأن بطنها تعتصرها وعدم القدرة على اخراج الغازات وانتفاخ في البطن
    - تعرضت لحادث حيث حصل لي نزيف خارجي و نزيف داخلي برأسي نتيجة الإصابة بالرأس مما أدى إلى الدخول في غيبوبة و نتج عن ذلك فقدان البصر من أحد العينين (اليسرى) و بعد الفحوصات العديدة هل يوجد تشخيص؟
    - الم البطن استبراد وما هوه العلاج
    - طلعلي كرة عند مدمع العين شو ممكن تكون وكيف ممكن أتخلص منها
    - انا اعاني من الألم في الظهر وفي الاكتاف وبين الاكتاف وعندما ابتلع الطعام أشعر بالألم الظهر والاكتاف وحتى اضطرابات في الرؤيه
    - حكه في العيون ولون احمر ودموع بعد الحك ويش الدواء المناسب
    - [والدي]{"entity": "sex", "value": "male"} يبلغ من العمر [78](age) عاما يعاني من الإمساك الشديدالمزمن ، هو مريض سكري و بروسطاطا يعاني من الإجهاد دائما فهو اصبح غير قادر على التحرك بشكل جيد يعاني من انتفاخ شديد جدا و غير قادر للذهاب الى الطبيب...
    - اعاني من تجشؤات واصوات مسموعة في البطن و الم في الجانب الايمن من البطن
    - أشعر بالم أسفل الصدر في الجهة اليسرى منذ فترة من الاعراض التي تضهر جراء هذا الالم الشعور بالدوار الشعور بالاختناق تنمل الاطراف القلق الشديد التبول بكثرة تنمل الجهة اليسرى خاصة في الرقبة
    - منذ أسابيع ظهرت لي حبة فوق عيني اليمنى ثم بعدها في أسفل عيني اليسرى ماذا أفعل لتزول هذه الحبوب
    - اعانى من انتفاخ عيونى جفن العليا و جفن السفلى انزعج منها واريد اعرف سبب او وصفة حتى اتخلص من انتفاخ و شكرا
    - [زوجتي]{"entity": "sex", "value": "female"} تعاني منذ زمن بعيد من غثيان و تقيؤ وفقدان الشهية في بعض الاحيان بدون الشعور بالم في المعدة او اي جزء من الجهاز الهضمي
    - إجابتي من اهل الاختصاص أعاني من ظبابية في الرؤية في العين اليمنى وزرت الطبيب وفحصني وقام بتصوير عيني و أخبرني انه لدي انتفاخ في شبكية العين.
    - أصبح بطني يؤلمني لدرجة وينفخ بطني و أسمع صوت الغازات كثيرة و الإسهال
    - اعانى دائما من الم المعده من زمن بعيد ويكون الالم مصاحب التقئ غالبا والاسهال او الامساك ولكننى اعانى من الامساك طوال الوقت
    - الألم من رأس المعده
    - عملت عمليه لعيني اليسرى عمليه زرع عدسه من جديديوجد الم شديد في العين استيقظ من النوم افتح عيني بصعوبه الرجاء المساعده
- synonym: female
  examples: |
    - انثى
    - بنت
    - صبية
    - حجة
    - فتاة
    - فتاه
    - بنوتة
    - صبيه
    - امراة
    - مرأة
    - زوجتي
    - عمتي
    - خالتي
    - زوجة
    - مرتي
    - بنتي
    - طفلتي
    - ابنتي
    - والدتي
    - امي
    - ماما
    - أختي
    - أمي
    - طفله
- synonym: male
  examples: |
    - ذكر
    - ولد
    - شب
    - حج
    - زلمة
    - رجل
    - فتى
    - ختيار
    - عجوز
    - زوجي
    - عمي
    - خالي
    - ولدي
    - ابني
    - طفلي
    - والدي
    - ابي
    - ابوي
    - بابا
